name: slskdn
base: core22
version: '0.24.1-slskdn.32'
summary: 🔋 The batteries included fork of slskd with 24+ new features
description: |
  The batteries included fork of slskd with 24+ new features: decentralized pods,
  content validation, swarm downloads, DHT mesh networking, auto-replace, wishlist,
  security hardening. Modern web UI for the Soulseek network.
grade: stable
confinement: strict
architectures:
  - amd64

apps:
  slskdn:
    command: slskd
    daemon: simple
    plugs: [network, network-bind, home, removable-media]
    environment:
      DOTNET_BUNDLE_EXTRACT_BASE_DIR: $SNAP_USER_COMMON/.net

parts:
  slskdn:
    plugin: dump
    source: https://github.com/snapetech/slskdn/releases/download/0.24.1-slskdn.32/slskdn-0.24.1-slskdn.32-linux-x64.zip
    source-checksum: sha256/97f8a416672c9721d6f20f95ab656621ae0804ff4f3be8654dc5f4814111ea97
    stage-packages:
      - libicu70
      - libssl3
