#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

"$repo_root/scripts/check-route-inventory.sh"
"$repo_root/scripts/check-controller-csrf.sh"
"$repo_root/scripts/check-anonymous-endpoints.sh"
"$repo_root/scripts/check-non-versioned-routes.sh"
"$repo_root/scripts/check-allowlist-drift.sh"
"$repo_root/scripts/check-sensitive-placeholders.sh"
"$repo_root/scripts/check-web-api-paths.sh"
"$repo_root/scripts/check-web-fetch-csrf.sh"
"$repo_root/scripts/check-web-mediacore-routes.sh"
"$repo_root/scripts/check-web-url-intent.sh"
"$repo_root/scripts/check-web-route-segment-encoding.sh"
"$repo_root/scripts/check-web-json-string-bodies.sh"
"$repo_root/scripts/check-web-list-shape-guards.sh"
"$repo_root/scripts/check-mutating-role-requirements.sh"
"$repo_root/scripts/check-async-task-observation.sh"
"$repo_root/scripts/check-async-void-handlers.sh"
"$repo_root/scripts/check-outbound-http-guards.sh"
"$repo_root/scripts/check-path-containment.sh"
"$repo_root/scripts/check-soulseek-network-health.sh"
"$repo_root/scripts/check-workflow-yaml-syntax.sh"
"$repo_root/scripts/check-workflow-trigger-policy.sh"
"$repo_root/scripts/check-codeql-dotnet-version.sh"
"$repo_root/scripts/check-dotnet-runtime-matrix.sh"
"$repo_root/scripts/check-release-asset-matrix.sh"
"$repo_root/scripts/check-flatpak-manifest-structure.sh"
"$repo_root/scripts/check-config-option-drift.sh"
"$repo_root/scripts/check-systemd-permission-matrix.sh"
"$repo_root/scripts/check-remediation-script-registry.sh"
"$repo_root/scripts/check-remediation-doc-commands.sh"

printf 'Remediation baseline checks passed.\n'
