# frozen_string_literal: true

class Slskdn < Formula
  desc "Soulseek Network Client - Next Generation"
  homepage "https://github.com/slskd/slskd"
  url "https://github.com/slskd/slskd/releases/download/v0.0.1/slskd-0.0.1-osx-x64.tar.gz"
  sha256 "PLACEHOLDER_SHA256" # Will be updated with actual release
  license "GPL-3.0-only"
  version "0.0.1"

  livecheck do
    url :homepage
    regex(/v?(\d+(?:\.\d+)+)/i)
  end

  bottle do
    root_url "https://github.com/slskd/slskd/releases/download/v0.0.1"
    sha256 cellar: :any_skip_relocation, catalina: "PLACEHOLDER_SHA256"
    sha256 cellar: :any_skip_relocation, big_sur: "PLACEHOLDER_SHA256"
    sha256 cellar: :any_skip_relocation, monterey: "PLACEHOLDER_SHA256"
  end

  depends_on "dotnet@6"

  def install
    # Install the .NET application
    libexec.install Dir["*"]

    # Create executable script
    (bin/"slskdn").write <<~EOS
      #!/bin/bash
      exec "#{Formula["dotnet@6"].opt_bin}/dotnet" "#{libexec}/slskd.dll" "$@"
    EOS

    # Set executable permissions
    chmod 0555, bin/"slskdn"
  end

  def post_install
    # Create default configuration if it doesn't exist
    config_dir = etc/"slskdn"
    config_dir.mkpath

    config_file = config_dir/"slskd.yml"
    unless config_file.exist?
      config_file.write <<~EOS
        # slskdN Configuration
        # Generated by Homebrew formula
        # Edit this file to customize your slskdN installation

        # Web UI settings
        web:
          enabled: true
          port: 5030
          https:
            disabled: true

        # Soulseek network settings
        soulseek:
          listen:
            port: 2234

        # Data directories (will be created if they don't exist)
        directories:
          shared: "~/slskd/shared"
          downloads: "~/slskd/downloads"
          incomplete: "~/slskd/incomplete"

        # Logging
        logger:
          level: info

        # Security (optional - configure as needed)
        # security:
        #   apiKeys:
        #     - "your-api-key-here"
        #   requireApiKey: false

        # Mesh features (advanced - optional)
        # mesh:
        #   enabled: false
        #   peerId: ""
        #   parent: ""
        EOS
    end

    # Create data directories
    (var/"slskdn").mkpath
    (var/"slskdn/shared").mkpath
    (var/"slskdn/downloads").mkpath
    (var/"slskdn/incomplete").mkpath

    # Set permissions
    chmod 0755, var/"slskdn"
    chmod 0755, var/"slskdn/shared"
    chmod 0755, var/"slskdn/downloads"
    chmod 0755, var/"slskdn/incomplete"
  end

  def caveats
    <<~EOS
      slskdN has been installed!

      📁 Configuration: #{etc}/slskdn/slskd.yml
      📁 Data directories: #{var}/slskdn/

      🚀 To start slskdN:
        brew services start slskdn

      🌐 Web UI will be available at: http://localhost:5030

      📖 First-time setup:
        1. Open http://localhost:5030 in your browser
        2. Create an admin account
        3. Configure your shared folders
        4. Start sharing and downloading!

      🔧 To configure slskdN:
        Edit #{etc}/slskdn/slskd.yml

      📊 To check status:
        brew services list | grep slskdn

      🛑 To stop slskdN:
        brew services stop slskdn

      📚 Documentation: https://github.com/slskd/slskd/wiki
      🐛 Issues: https://github.com/slskd/slskd/issues

      Note: Soulseek network requires a valid username/password.
      Create an account at https://www.slsknet.org if you don't have one.
    EOS
  end

  service do
    run [opt_bin/"slskdn"]
    keep_alive true
    working_dir var/"slskdn"
    log_path var/"log/slskdn.log"
    error_log_path var/"log/slskdn.error.log"
    environment_variables({
      "HOME" => var/"slskdn",
      "SLSKD_CONFIG" => etc/"slskdn/slskd.yml"
    })
  end

  test do
    # Basic test to ensure the binary runs
    system "#{bin}/slskdn", "--version"

    # Test that configuration file was created
    assert_predicate etc/"slskdn/slskd.yml", :exist?

    # Test that data directories were created
    assert_predicate var/"slskdn", :directory?
    assert_predicate var/"slskdn/shared", :directory?
    assert_predicate var/"slskdn/downloads", :directory?
  end
end

