// <copyright file="TrackAcquisitionPlan.cs" company="slskd Team">
//     Copyright (c) slskd Team. All rights reserved.
//
//     This program is free software: you can redistribute it and/or modify
//     it under the terms of the GNU Affero General Public License as published
//     by the Free Software Foundation, either version 3 of the License, or
//     (at your option) any later version.
//
//     This program is distributed in the hope that it will be useful,
//     but WITHOUT ANY WARRANTY; without even the implied warranty of
//     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//     GNU Affero General Public License for more details.
//
//     You should have received a copy of the GNU Affero General Public License
//     along with this program.  If not, see https://www.gnu.org/licenses/.
// </copyright>

namespace slskd.VirtualSoulfind.v2.Planning
{
    using System;
    using System.Collections.Generic;
    using slskd.VirtualSoulfind.v2.Backends;
    using slskd.VirtualSoulfind.v2.Sources;

    /// <summary>
    ///     Fallback mode for a plan step.
    /// </summary>
    public enum PlanStepFallbackMode
    {
        /// <summary>Try candidates in sequence (cascade).</summary>
        Cascade,

        /// <summary>Try all candidates in parallel (fan-out).</summary>
        FanOut,
    }

    /// <summary>
    ///     A step in a track acquisition plan.
    /// </summary>
    /// <remarks>
    ///     Each step represents trying one backend with a set of candidates.
    ///     Steps are executed in order, with fallback to the next step on failure.
    /// </remarks>
    public sealed class PlanStep
    {
        /// <summary>
        ///     Gets or initializes the backend type for this step.
        /// </summary>
        public ContentBackendType Backend { get; init; }

        /// <summary>
        ///     Gets or initializes the source candidates to try.
        /// </summary>
        public IReadOnlyList<SourceCandidate> Candidates { get; init; }

        /// <summary>
        ///     Gets or initializes the maximum number of parallel attempts.
        /// </summary>
        public int MaxParallel { get; init; } = 1;

        /// <summary>
        ///     Gets or initializes the timeout for this step.
        /// </summary>
        public TimeSpan Timeout { get; init; }

        /// <summary>
        ///     Gets or initializes the fallback mode.
        /// </summary>
        public PlanStepFallbackMode FallbackMode { get; init; }
    }

    /// <summary>
    ///     Represents a plan for acquiring a track from multiple potential sources.
    /// </summary>
    /// <remarks>
    ///     The plan is generated by the Multi-Source Planner based on:
    ///     - Available source candidates (from source registry + backends)
    ///     - Domain rules (e.g., non-music can't use Soulseek)
    ///     - MCP filtering (skip blocked/quarantined)
    ///     - Per-backend caps and work budgets
    ///     - Trust and quality scores
    /// </remarks>
    public sealed class TrackAcquisitionPlan
    {
        /// <summary>
        ///     Gets or initializes the track ID this plan is for.
        /// </summary>
        public string TrackId { get; init; }

        /// <summary>
        ///     Gets or initializes the desired track information.
        /// </summary>
        public object? DesiredTrack { get; init; }

        /// <summary>
        ///     Gets or initializes the planning mode used.
        /// </summary>
        public PlanningMode Mode { get; init; }

        /// <summary>
        ///     Gets or initializes the plan status.
        /// </summary>
        public PlanStatus Status { get; init; }

        /// <summary>
        ///     Gets or initializes when this plan expires.
        /// </summary>
        public DateTimeOffset? ExpiresAt { get; init; }

        /// <summary>
        ///     Gets or initializes the error message if planning failed.
        /// </summary>
        public string? ErrorMessage { get; init; }

        /// <summary>
        ///     Gets or initializes the ordered list of steps to execute.
        /// </summary>
        /// <remarks>
        ///     Steps are tried in order. If a step fails, move to the next.
        /// </remarks>
        public IReadOnlyList<PlanStep> Steps { get; init; }

        /// <summary>
        ///     Gets or initializes when this plan was created.
        /// </summary>
        public DateTimeOffset CreatedAt { get; init; }

        /// <summary>
        ///     Gets whether this plan has any actionable steps.
        /// </summary>
        public bool IsExecutable => Steps != null && Steps.Count > 0;
    }
}
